//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiltonDeluxe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bokning
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bokning()
        {
            this.Faktura1 = new HashSet<Faktura>();
        }
    
        public int BokningID { get; set; }
        public System.DateTime AnkomstDatum { get; set; }
        public System.DateTime AvreseDatum { get; set; }
        public int KundID { get; set; }
        public int RumID { get; set; }
        public Nullable<int> ExtraSang { get; set; }
        public Nullable<System.DateTime> BokningDatum { get; set; }
        public Nullable<int> FakturaID { get; set; }
    
        public virtual Faktura Faktura { get; set; }
        public virtual Kund Kund { get; set; }
        public virtual Rum Rum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Faktura> Faktura1 { get; set; }
    }
}
