//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiltonDeluxe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Faktura()
        {
            this.Bokning = new HashSet<Bokning>();
        }
    
        public int FakturaID { get; set; }
        public int Belopp { get; set; }
        public string Hanterad { get; set; }
        public int BokningID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bokning> Bokning { get; set; }
        public virtual Bokning Bokning1 { get; set; }
    }
}
