//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiltonDeluxe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kund
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kund()
        {
            this.Bokning = new HashSet<Bokning>();
        }
    
        public int KundID { get; set; }
        public string ForNamn { get; set; }
        public string EfterNamn { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bokning> Bokning { get; set; }
    }
}
