//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiltonDeluxe.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HiltonDeluxeEntities8 : DbContext
    {
        public HiltonDeluxeEntities8()
            : base("name=HiltonDeluxeEntities8")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bokning> Bokning { get; set; }
        public virtual DbSet<Faktura> Faktura { get; set; }
        public virtual DbSet<Kund> Kund { get; set; }
        public virtual DbSet<Rum> Rum { get; set; }
        public virtual DbSet<RumTyp> RumTyp { get; set; }
    }
}
