//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HiltonDeluxe.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rum()
        {
            this.Bokning = new HashSet<Bokning>();
        }
    
        public int RumID { get; set; }
        public int RumTypID { get; set; }
        public string RumNamn { get; set; }
        public int Pris { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bokning> Bokning { get; set; }
        public virtual RumTyp RumTyp { get; set; }
    }
}
